# Socceraction

## Libraries and Constants

In [1]:
# Import libraries
import socceraction.spadl as spadl

from pathlib import Path
from socceraction.data.statsbomb import StatsBombLoader

In [2]:
# Ignore warnings
import warnings

warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", message="Inferred xy_fidelity_version=2.", category=UserWarning)

In [3]:
# Define the data directory
DATA_DIR = Path("../data")

## StatsBomb API

In [4]:
# Define the StatsBomb API as local
statsbomb_data_dir = str(DATA_DIR)
SBL = StatsBombLoader(getter="local", root=statsbomb_data_dir)

In [5]:
# Load the competitions data
competitions_df = SBL.competitions()
competitions_df

,season_id,competition_id,competition_name,country_name,competition_gender,season_name
0,281,9,1. Bundesliga,Germany,male,2023/2024
1,27,9,1. Bundesliga,Germany,male,2015/2016
2,107,1267,African Cup of Nations,Africa,male,2023
3,4,16,Champions League,Europe,male,2018/2019
4,1,16,Champions League,Europe,male,2017/2018
...,...,...,...,...,...,...
69,43,55,UEFA Euro,Europe,male,2020
70,75,35,UEFA Europa League,Europe,male,1988/1989
71,106,53,UEFA Women's Euro,Europe,female,2022
72,107,72,Women's World Cup,International,female,2023
73,30,72,Women's World Cup,International,female,2019

In [6]:
# Load the games data for a specific competition and season
# For example, the  UEFA Euro 2024
games_df = SBL.games(competition_id=55, season_id=282).set_index("game_id")
games_df.sort_values(by="game_day", ascending=False, inplace=True)
games_df.head(n=7)

,season_id,competition_id,competition_stage,game_day,game_date,home_team_id,away_team_id,home_score,away_score,venue,referee
game_id,,,,,,,,,,,
3943043,282,55,Final,7,2024-07-14 22:00:00,772,768,2,1,Olympiastadion Berlin,François Letexier
3942819,282,55,Semi-finals,6,2024-07-10 22:00:00,941,768,1,2,Signal-Iduna-Park,Felix Zwayer
3942752,282,55,Semi-finals,6,2024-07-09 22:00:00,772,771,2,1,Allianz Arena,Slavko Vinčić
3942382,282,55,Quarter-finals,5,2024-07-06 22:00:00,941,909,2,1,Olympiastadion Berlin,Clément Turpin
3942349,282,55,Quarter-finals,5,2024-07-05 22:00:00,780,771,0,0,Volksparkstadion,Michael Oliver
3942227,282,55,Quarter-finals,5,2024-07-06 19:00:00,768,773,1,1,Merkur Spiel-Arena,Daniele Orsato
3942226,282,55,Quarter-finals,5,2024-07-05 19:00:00,772,770,2,1,MHPArena,Anthony Taylor

In [7]:
# Load the teams data for the final game of the UEFA Euro 2024
teams_df = SBL.teams(game_id=3943043)
teams_df

   team_id team_name
0      772     Spain
1      768   England

In [8]:
# Load the players data for the final game of the UEFA Euro 2024
players_df = SBL.players(game_id=3943043)
players_df

,game_id,team_id,player_id,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played
0,3943043,772,3042,Mikel Merino Zazón,Mikel Merino,6,False,0,Substitute,6
1,3943043,772,3477,Álvaro Borja Morata Martín,Álvaro Morata,7,True,23,Center Forward,69
2,3943043,772,4353,Aymeric Laporte,None,14,True,5,Left Center Back,96
3,3943043,772,5202,José Ignacio Fernández Iglesias,Nacho,4,False,0,Substitute,12
4,3943043,772,5721,Daniel Carvajal Ramos,Daniel Carvajal,2,True,2,Right Back,96
5,3943043,772,6655,Fabián Ruiz Peña,Fabián Ruiz,8,True,11,Left Defensive Midfield,96
6,3943043,772,6685,Mikel Oyarzabal Ugarte,Mikel Oyarzabal,21,False,0,Substitute,27
7,3943043,772,6765,Rodrigo Hernández Cascante,Rodri,16,True,9,Right Defensive Midfield,45
8,3943043,772,11748,Unai Simón Mendibil,Unai Simón,23,True,1,Goalkeeper,96
9,3943043,772,16532,Daniel Olmo Carvajal,Daniel Olmo,10,True,19,Center Attacking Midfield,96
10,3943043,772,17620,Marc Cucurella Saseta,Marc Cucurella,24,True,6,Left Back,96
11,3943043,772,22128,Robin Aime Robert Le Normand,Robin Le Normand,3,True,3,Right Center Back,84
12,3943043,772,24921,Martín Zubimendi Ibáñez,Martín Zubimendi,18,False,0,Substitute,51
13,3943043,772,68574,Nicholas Williams Arthuer,Nico Williams,17,True,21,Left Wing,96
14,3943043,772,316046,Lamine Yamal Nasraoui Ebana,Lamine Yamal,19,True,17,Right Wing,90
15,3943043,768,3205,Kyle Walker,None,2,True,2,Right Back,96
16,3943043,768,3244,John Stones,None,5,True,3,Right Center Back,96
17,3943043,768,3382,Luke Shaw,None,3,True,6,Left Back,96
18,3943043,768,3468,Jordan Pickford,None,1,True,1,Goalkeeper,96
19,3943043,768,3834,Ivan Toney,None,17,False,0,Substitute,5
20,3943043,768,3943,Declan Rice,None,4,True,11,Left Defensive Midfield,96
21,3943043,768,4354,Phil Foden,None,11,True,19,Center Attacking Midfield,91
22,3943043,768,4760,Ollie Watkins,None,19,False,0,Substitute,34
23,3943043,768,10955,Harry Kane,None,9,True,23,Center Forward,62
24,3943043,768,22084,Bukayo Saka,None,7,True,17,Right Wing,96
25,3943043,768,30714,Jude Bellingham,None,10,True,21,Left Wing,96
26,3943043,768,34526,Marc Guehi,None,6,True,5,Left Center Back,96
27,3943043,768,39461,Cole Palmer,None,24,False,0,Substitute,25
28,3943043,768,99174,Kobbie Mainoo,None,26,True,9,Right Defensive Midfield,71

In [9]:
# Load the events data for the final game of the UEFA Euro 2024
events_df = SBL.events(game_id=3943043)
events_df.head()

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,team_name,duration,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress
0,3943043,50aa204f-5d65-4145-8597-5d5628fb7898,1,772,NaN,35,Starting XI,1,0 days 00:00:00,0,...,Spain,0.000000,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False
1,3943043,a279cbee-9ab3-4cfb-9c51-27cacc1bf2a2,1,768,NaN,35,Starting XI,2,0 days 00:00:00,0,...,England,0.000000,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False
2,3943043,d2126e70-9f04-4bb7-ba2b-9377836d1757,1,768,NaN,18,Half Start,3,0 days 00:00:00,0,...,England,0.000000,{},[54d78bfa-4146-42bd-acdc-97bcd393dd81],NaN,NaN,NaN,NaN,False,False
3,3943043,54d78bfa-4146-42bd-acdc-97bcd393dd81,1,772,NaN,18,Half Start,4,0 days 00:00:00,0,...,Spain,0.000000,{},[d2126e70-9f04-4bb7-ba2b-9377836d1757],NaN,NaN,NaN,NaN,False,False
4,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,768,99174.0,30,Pass,5,0 days 00:00:00.340000,0,...,England,2.529454,"{'pass': {'recipient': {'id': 3468, 'name': 'J...",[d64668c7-747c-4a7d-912c-e1c3ff357a67],Kobbie Mainoo,9.0,Right Defensive Midfield,"[60.0, 40.0]",False,False

In [10]:
# Load the 360 data for the final game of the UEFA Euro 2024
events_360_df = SBL.events(game_id=3943043, load_360=True)
events_360_df.head()

,game_id,event_id,period_id,team_id,player_id,type_id,type_name,index,timestamp,minute,...,extra,related_events,player_name,position_id,position_name,location,under_pressure,counterpress,visible_area_360,freeze_frame_360
0,3943043,50aa204f-5d65-4145-8597-5d5628fb7898,1,772,NaN,35,Starting XI,1,0 days 00:00:00,0,...,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
1,3943043,a279cbee-9ab3-4cfb-9c51-27cacc1bf2a2,1,768,NaN,35,Starting XI,2,0 days 00:00:00,0,...,"{'tactics': {'formation': 4231, 'lineup': [{'p...",[],NaN,NaN,NaN,NaN,False,False,NaN,NaN
2,3943043,d2126e70-9f04-4bb7-ba2b-9377836d1757,1,768,NaN,18,Half Start,3,0 days 00:00:00,0,...,{},[54d78bfa-4146-42bd-acdc-97bcd393dd81],NaN,NaN,NaN,NaN,False,False,NaN,NaN
3,3943043,54d78bfa-4146-42bd-acdc-97bcd393dd81,1,772,NaN,18,Half Start,4,0 days 00:00:00,0,...,{},[d2126e70-9f04-4bb7-ba2b-9377836d1757],NaN,NaN,NaN,NaN,False,False,NaN,NaN
4,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,768,99174.0,30,Pass,5,0 days 00:00:00.340000,0,...,"{'pass': {'recipient': {'id': 3468, 'name': 'J...",[d64668c7-747c-4a7d-912c-e1c3ff357a67],Kobbie Mainoo,9.0,Right Defensive Midfield,"[60.0, 40.0]",False,False,"[76.727979231533, 80.0, 43.48260274825104, 80....","[{'teammate': True, 'actor': False, 'keeper': ..."

## SPADL

In [11]:
# Convert the events data of the final game of the UEFA Euro 2024 to SPADL actions
home_team_id = games_df.at[3943043, "home_team_id"]
actions_df = spadl.statsbomb.convert_to_actions(events_df, home_team_id=home_team_id)
actions_df

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,type_id,result_id,bodypart_id,action_id
0,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,0.340,768,99174.0,52.54375,33.9575,82.81875,32.9375,0,1,5,0
1,3943043,9c107df3-a3c8-4ad5-bc35-00214087a105,1,2.870,768,3468.0,82.81875,32.9375,79.93125,26.8175,21,1,0,1
2,3943043,237201b8-aef8-4823-b282-e82875795c07,1,4.742,768,3468.0,79.93125,26.8175,0.04375,57.5025,0,0,4,2
3,3943043,238f44cb-0f18-4217-85b5-8cc6345278fe,1,34.440,772,11748.0,5.99375,34.3825,7.91875,19.4225,22,1,4,3
4,3943043,987a3f1e-4dc4-4833-8896-5513e35c3fc5,1,35.658,772,22128.0,7.91875,19.4225,7.74375,19.4225,21,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,3943043,5d909b16-f11b-4d1c-8657-7eb5421ed102,2,2860.833,768,3468.0,54.73125,30.5575,12.46875,50.1075,3,0,4,1878
1879,3943043,4a610ec1-edf3-4066-bd69-cb2a28f2981c,2,2863.751,772,4353.0,12.46875,50.1075,10.89375,65.9175,18,1,1,1879
1880,3943043,c11721ac-1ddd-4a7d-8ee9-6ba005b6380f,2,2865.814,768,22084.0,10.89375,65.9175,12.73125,66.0025,21,1,0,1880
1881,3943043,8eab51fc-0835-4fdb-8fe2-9c38fc38c46b,2,2867.318,768,22084.0,12.73125,66.0025,12.73125,66.0025,8,0,0,1881
1882,3943043,9be6bb15-7db5-483e-aee7-44430f07c38f,2,2929.145,772,3042.0,86.05625,45.9425,86.05625,45.9425,8,0,0,1882

In [12]:
# Replace IDs with names in the actions DataFrame
actions_df = spadl.add_names(actions_df).merge(SBL.teams(game_id=3943043)).merge(SBL.players(game_id=3943043))
actions_df

,game_id,original_event_id,period_id,time_seconds,team_id,player_id,start_x,start_y,end_x,end_y,...,result_name,bodypart_name,team_name,player_name,nickname,jersey_number,is_starter,starting_position_id,starting_position_name,minutes_played
0,3943043,152820f0-6ca9-4df3-943b-a67d568ff472,1,0.340,768,99174.0,52.54375,33.9575,82.81875,32.9375,...,success,foot_right,England,Kobbie Mainoo,None,26,True,9,Right Defensive Midfield,71
1,3943043,9c107df3-a3c8-4ad5-bc35-00214087a105,1,2.870,768,3468.0,82.81875,32.9375,79.93125,26.8175,...,success,foot,England,Jordan Pickford,None,1,True,1,Goalkeeper,96
2,3943043,237201b8-aef8-4823-b282-e82875795c07,1,4.742,768,3468.0,79.93125,26.8175,0.04375,57.5025,...,fail,foot_left,England,Jordan Pickford,None,1,True,1,Goalkeeper,96
3,3943043,238f44cb-0f18-4217-85b5-8cc6345278fe,1,34.440,772,11748.0,5.99375,34.3825,7.91875,19.4225,...,success,foot_left,Spain,Unai Simón Mendibil,Unai Simón,23,True,1,Goalkeeper,96
4,3943043,987a3f1e-4dc4-4833-8896-5513e35c3fc5,1,35.658,772,22128.0,7.91875,19.4225,7.74375,19.4225,...,success,foot,Spain,Robin Aime Robert Le Normand,Robin Le Normand,3,True,3,Right Center Back,84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,3943043,5d909b16-f11b-4d1c-8657-7eb5421ed102,2,2860.833,768,3468.0,54.73125,30.5575,12.46875,50.1075,...,fail,foot_left,England,Jordan Pickford,None,1,True,1,Goalkeeper,96
1879,3943043,4a610ec1-edf3-4066-bd69-cb2a28f2981c,2,2863.751,772,4353.0,12.46875,50.1075,10.89375,65.9175,...,success,head,Spain,Aymeric Laporte,None,14,True,5,Left Center Back,96
1880,3943043,c11721ac-1ddd-4a7d-8ee9-6ba005b6380f,2,2865.814,768,22084.0,10.89375,65.9175,12.73125,66.0025,...,success,foot,England,Bukayo Saka,None,7,True,17,Right Wing,96
1881,3943043,8eab51fc-0835-4fdb-8fe2-9c38fc38c46b,2,2867.318,768,22084.0,12.73125,66.0025,12.73125,66.0025,...,fail,foot,England,Bukayo Saka,None,7,True,17,Right Wing,96
1882,3943043,9be6bb15-7db5-483e-aee7-44430f07c38f,2,2929.145,772,3042.0,86.05625,45.9425,86.05625,45.9425,...,fail,foot,Spain,Mikel Merino Zazón,Mikel Merino,6,False,0,Substitute,6